//_________________________________________ ENDPOINTS______________________________________//

//1 - Signup 

POST http://localhost:3003/users/signup
Content-Type: application/json

{
   "name": "teste", 
   "email": "teste@email.com",
   "password": "123456",
   "role": "admin"
}

###
//2 - Login

POST http://localhost:3003/users/login
Content-Type: application/json

{
   "email": "teste@email.com",
   "password": ""
}

###

//3 - GET ALL USERS

GET http://localhost:3003/users/allUsers

###

POST http://localhost:3003/shows/create
Content-Type: application/json

{
   "week_day": "Friday", 
   "start_time": 8, 
   "end_time": 10, 
   "band_id": 1
}


